import React from "react";
const dataContext = React.createContext({
  csvHeader: [],
  isLogin: false,
  isLoading: true,
  primaryKey: "",
  imageColName: "",
  skippingKey: [],
  firstInputFileName: "",
  secondInputFileName: "",
  firstInputCsvFiles: [],
  secondInputCsvFiles: [],
  correctedCsv: {},
  zipImageFile: [],
  imageMappedData: [],
  fileId: "",
  csvFile: [],
  csvDataWithImage: [],
  userData: {},
  loginData: {},
  uploadZipImage: [],
  formFeilds: [],
  templateData: {},

  modifyTemplateData: () => {},
  modifyUserData: () => {},
  modifyLoginData: () => {},
  modifyIsLoading: () => {},
  modifyIslogin: () => {},
  addToCsvHeader: () => {},
  addToPrimaryKey: () => {},
  addToSkippingKey: () => {},
  addFirstInputFileName: () => {},
  addSecondInputFileName: () => {},
  addFirstInputCsvFile: () => {},
  addSecondInputCsvFile: () => {},
  addToCorrectedCsv: () => {},
  addZipImageFile: () => {},
  setImageColName: () => {},
  setImageMappedData: () => {},
  modifyFileId: () => {},
  setCsvFile: () => {},
  setCsvDataWithImage: () => {},
  setUploadZipImage: () => {},
  setFormFeilds: () => {},
});

export default dataContext;
